<html>
	<head>
		<script type="text/javascript" src="../js/coverreport.js">

		</script><script type="text/javascript">
			RANGES_11 = [
  ];
		</script><link rel="stylesheet" type="text/css" href="../css/coverreport.css" />
	</head><body>
		<code id="src11" class="dotCoverSource"><pre>// ------------------------------------------------------------------------------
//  &lt;auto-generated&gt;
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  &lt;/auto-generated&gt;
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Patterns.Specifications.Features.ExceptionHandling
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute(&quot;TechTalk.SpecFlow&quot;, &quot;1.9.0.77&quot;)]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute(&quot;Exception Handling&quot;)]
    public partial class ExceptionHandlingFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 &quot;ExceptionHandling.feature&quot;
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo(&quot;en-US&quot;), &quot;Exception Handling&quot;, &quot;As a developer, I want to be able to isolate the scope of error-prone code,\r\nand &quot; +
                    &quot;I want the ability to either rely on a basic error handling policy,\r\nor provide &quot; +
                    &quot;my own logic to respond to exceptions.&quot;, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute(&quot;Try.Get (Normal)&quot;)]
        public virtual void Try_GetNormal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo(&quot;Try.Get (Normal)&quot;, ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given(&quot;I have mapped the default error strategy to store exceptions&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Given &quot;);
#line 8
 testRunner.When(&quot;I try to get the return value of a normal function&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;When &quot;);
#line 9
 testRunner.Then(&quot;the return value should be the expected return value&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Then &quot;);
#line 10
 testRunner.And(&quot;there should not be an error&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;And &quot;);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute(&quot;Try.Get (Exception)&quot;)]
        public virtual void Try_GetException()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo(&quot;Try.Get (Exception)&quot;, ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given(&quot;I have mapped the default error strategy to store exceptions&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Given &quot;);
#line 14
 testRunner.When(&quot;I try to get the return value of a function that throws an exception&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;When &quot;);
#line 15
 testRunner.Then(&quot;the return value should be the default value for that type&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Then &quot;);
#line 16
 testRunner.And(&quot;there should be an error&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;And &quot;);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute(&quot;Try.Get (Exception with Custom Handler)&quot;)]
        public virtual void Try_GetExceptionWithCustomHandler()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo(&quot;Try.Get (Exception with Custom Handler)&quot;, ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given(&quot;I have mapped the custom error strategy to store exceptions&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Given &quot;);
#line 20
 testRunner.When(&quot;I try to get the return value of a function that throws an exception, providing t&quot; +
                    &quot;he custom strategy&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;When &quot;);
#line 21
 testRunner.Then(&quot;the return value should be the default value for that type&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Then &quot;);
#line 22
 testRunner.And(&quot;there should be an error&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;And &quot;);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute(&quot;Try.Do (Normal)&quot;)]
        public virtual void Try_DoNormal()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo(&quot;Try.Do (Normal)&quot;, ((string[])(null)));
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
 testRunner.Given(&quot;I have mapped the default error strategy to store exceptions&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Given &quot;);
#line 26
 testRunner.When(&quot;I try to run a normal action&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;When &quot;);
#line 27
 testRunner.Then(&quot;there should not be an error&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Then &quot;);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute(&quot;Try.Do (Exception)&quot;)]
        public virtual void Try_DoException()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo(&quot;Try.Do (Exception)&quot;, ((string[])(null)));
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given(&quot;I have mapped the default error strategy to store exceptions&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Given &quot;);
#line 31
 testRunner.When(&quot;I try to run an action that throws an exception&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;When &quot;);
#line 32
 testRunner.Then(&quot;there should be an error&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Then &quot;);
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute(&quot;Try.Do (Exception with Custom Handler)&quot;)]
        public virtual void Try_DoExceptionWithCustomHandler()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo(&quot;Try.Do (Exception with Custom Handler)&quot;, ((string[])(null)));
#line 34
this.ScenarioSetup(scenarioInfo);
#line 35
 testRunner.Given(&quot;I have mapped the custom error strategy to store exceptions&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Given &quot;);
#line 36
 testRunner.When(&quot;I try to run an action that throws an exception, providing the custom strategy&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;When &quot;);
#line 37
 testRunner.Then(&quot;there should be an error&quot;, ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), &quot;Then &quot;);
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
</pre></code><script type="text/javascript">
			applyranges('src11', RANGES_11)
		</script>
	</body>
</html>